.babelrc
.eslintrc.json
.gitignore
client/app.js
client/index.js
package-lock.json
package.json
seed.js
server/api/index.js
server/api/testRoute.js
server/db/db.js
server/db/index.js
server/index.js
static/index.html
webpack.config.js

This is a basic boilerplate with express and sequelize.
** Make sure to NPM install and createDB sphinx

Basic boilerplate with express and sequelize

---

server/index.js
static/index.html

* Two small bug fixes to the index.html in static and index.js in server from the PWA modification

PWA bug fix

---

.travis.yml
package-lock.json
package.json
server/db/index.js
server/db/models/channelUser.js
server/db/models/posts.js
server/db/models/users.js
tests/dbTests.js

Wrote up 2 quick tests. Can expand if you think we should. Let me know, otherwise these test will always pass unless we change up our user model.

added quick test that will pass for now

---

static/offline.html
static/service-worker.js

PWA offline.html catch

---

client/app.css
client/app.js
client/components/BottomMenu/BottomMenu.css
client/components/BottomMenu/BottomMenu.js
client/components/Burger/Burger.css
client/components/Burger/Burger.js
client/components/SlideMenu/SlideMenu.css
client/components/SlideMenu/SlideMenu.js
client/components/container/Container.css
client/components/container/Container.js
client/index.js
client/redux/nav/action/nav.action.js
client/redux/nav/reducer/nav.reducer.js
client/redux/nav/type/nav.type.js
client/redux/rootReducer.js
client/redux/store.js
static/index.html
static/main.css

** Basic Front End Components with slide menu and minor css

Basic front end components

---

client/app.js
client/index.js
client/redux/nav/action/nav.action.js
client/redux/nav/reducer/nav.reducer.js
client/redux/nav/type/nav.type.js
client/redux/rootReducer.js
client/redux/store.js

basic redux

---

client/components/MapView.js
client/components/container/Container.js
seed.js
server/db/models/messages.js

- Changes to seed to fix longitude
- Google maps component displaying (needs some styling work)
- Message markers displaying on map

maps component working with message markers

---

client/components/MapView.js
package-lock.json
package.json

- Cleaned up MapView component
- Added location listener with blue dot marker for user's current location

Google maps

---

client/components/MapView.js
static/index.html

- Added distance calculator which informs message marker display and functionality (currently set to 10000 meters for easier testing, can be changed via `minDistance` variable in `MapView.js`)

Distance calculator

---

client/app.js
client/components/Channel/SearchFrom.js
client/components/SlideMenu/SlideMenu.js
client/components/login/logIn.js
client/redux/authentication/authentication.js

Changed <Link> tags to <a> tags to avoid errors; removed duplicate mapDispatch

some fixes

---

client/components/SlideMenu/SlideMenu.css

small css edit

---

client/app.js
client/components/SlideMenu/SlideMenu.js
client/utils/utils.js
package-lock.json
package.json
server/api/index.js
server/api/messages.js
server/api/subscriptions.js
server/db/index.js
server/db/models/subscriptions.js
static/index.html
static/manifest.json
static/service-worker.js
utils.js

* Push messages across clients and subscribers
* added subscriber model and routing
* added webpush code to messages Post route - the code is clearly indicated between comments
* cleaned up some relevant console logs 
**** As usual, I've disabled the service worker on this push so you won't see any changes.

Push Messages

---

client/app.js
client/components/Channel/ChannelsList.js
client/components/Channel/MyChannelLineItem.js
client/components/Channel/MyChannels.js
client/redux/channels.js
server/api/channelUsers.js
server/api/channels.js

- Added thunks for sub and unsub.
- Added buttons and functionality on my channels to unsub and sub on search.
- Both functionalities work for testing but front end component behavior needs adjusting (ie. needing to refresh to show changes on mychannels when unsubscribing). 
- Moved search to the search icon on bottom menu.
Todos:
- Complete the todos in comments for channels - **Will work to this tonight**
- Fix thunk to grab the channel JSON from /api/channel/:id -  **Will work to this tonight**
- Create channel info component
- Move MyChannels to side bar & filter when clicking on channel
- Add channel

Uploading channel stuff

---

client/components/EditAccount/EditAccount.js
client/components/SignUp/SignUp.css
client/components/SignUp/SignUp.js
client/components/SlideMenu/SlideMenu.js
client/redux/activeUser/activeUser.js
client/redux/authentication/authentication.js
seed.js
server/api/index.js
server/db/models/users.js

signup working, all user paths redirect to map, worked on Seed file

signUp and Seed

---

client/app.css
client/app.js
client/components/BottomMenu/BottomMenu.css
client/components/BottomMenu/BottomMenu.js
client/components/Burger/Burger.js
client/components/Feed/feed.css
client/components/Feed/feed.js
client/components/MapView.js
client/components/SignUp/SignUp.css
client/components/SlideMenu/SlideMenu.css
server/api/channels.js
utils.js

some css styling

---

client/components/message/AddMessage.js

add message fix

---

client/app.js
client/components/MapView.js
client/components/message/AddMessage.js
client/components/message/LinkTest.js
client/components/message/PostLink.js
client/components/message/Upload.js
client/redux/messages.js
package-lock.json
package.json
seed.js
server/db/models/messages.js
static/index.html

**Run `npm i` and `npm run seed`**
- User can upload a link using "Send Link" button
- User can view a link using React Player (YouTube, Facebook, SoundCloud, Vimeo, etc. - see more here: https://www.npmjs.com/package/react-player)
- Added Jane Block to seed so that we can more easily test sending and viewing messages
- FYI, once a message is read it does not seem to be updating on redux store, as the marker is still visible and message is still viewable.

Upload link

---

client/components/MapView.js
client/redux/messages.js
seed.js
server/api/messages.js
server/index.js

read messages fix

---

client/components/Welcome/LandingPage.js
client/components/Welcome/landing.css
package-lock.json

style landing

---

client/app.css
client/components/Feed/feed.js
client/redux/activeUser/activeUser.js
client/redux/authentication/authentication.js
client/redux/users/users.js
server/db/models/users.js
server/index.js

feed updated

---

client/components/Channel/ChannelsList.js
client/components/Channel/MyChannelLineItem.js
client/components/Channel/MyChannels.js
client/components/SlideMenu/SlideMenu.css
client/redux/channels.js
client/redux/messages.js
server/api/channels.js

filter on click working need to DRY and add styling to show button clicked

Filter is now working

---

client/components/MapView.js
client/components/SelectMedia/Selectmedia.js
client/components/SlideMenu/SlideMenu.css
client/components/message/AddMessage.js
client/utils/utils.js

new message flow

---

client/components/Feed/feed.js
client/components/MapView.css
client/components/MapView.js
client/redux/messages.js
server/api/messages.js
utils.js

voting on messages

---

.eslintrc.json
client/app.js
client/components/Channel/MyChannelLineItem.js
client/components/Channel/MyChannels.js
client/components/MapView.js
client/components/SlideMenu/SlideMenu.js
package-lock.json
package.json

fixed linter
improved filter function
added button for edit channel

Doing things for things

---

client/components/Channel/EditChannel.js
seed.js
server/db/models/messages.js

Changed weird shit channel
Updated lat/ long and radius to smaller region so messages wouldn't appear in water.
Messages are still appearing red even though the radius is much smaller now?? @lachlanglen  can we discuss this

changed channel and lat/longs

---

client/components/MapView.js
client/components/SelectMedia/Selectmedia.js
client/components/message/AddMessage.js
client/components/message/PostSuccess.js
client/components/message/TakePhoto.css
client/components/message/TakePhoto.js
client/components/message/message.css

Worked on button consistency for photo upload and success page
Will continue to work on this, not complete for all media types

Button consistency for uploading messages 
